DATASET_ID = "tracking"
TABLE_ID = "events"
LOCATION = "europe-west1"
DAILY_SALT = "1324254"
CLIENT_ID_COOKIE_NAME = "clid_"
HASH_COOKIE_NAME = "abh_"
ACCESS_TOKEN_COOKIE_NAME = "mjs_session"
CF_URL = "cloud_function_url"